import requests
import json

OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL = "dolphin-llama3:8b"

SYSTEM_PROMPT = (
    "You are a cybersecurity lab analyst. "
    "Generate ONLY investigation questions. "
    "Do NOT repeat questions already asked. If this lab has been posted before, ask deeper, different questions or skip posting."

)

def analyze_text(input_text: str) -> str:
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Lab data:\n{input_text}\n\nGenerate 4–5 questions."}
        ],
        "stream": True
    }

    response = requests.post(
        OLLAMA_URL,
        json=payload,
        stream=True,
        timeout=None   # 🔥 KEY FIX: never timeout while streaming
    )

    output = ""
    for line in response.iter_lines():
        if not line:
            continue
        data = json.loads(line.decode("utf-8"))
        output += data["message"].get("content", "")
        if data.get("done"):
            break

    return f"""
### 🧪 Lab Investigation Questions

{output}

*(Generated by Matrix)*
"""

